### ISSUE TITLE
ホーム画面にあるヘッダーのサイズを変更すると、文字がメインコンテンツにかぶってしまうのを直す

### ISSUE THREAD

**Issue by mikanmatsuri** [mikanmatsuri/portfolio#21]
![image](https://user-images.githubusercontent.com/40571891/79993483-c4addc00-84ef-11ea-88a5-789316fc6aac.png)

**Comment by AlexanderKupriyanov** [comment]
これすでに直した気がするけど違う？

**Comment by mikanmatsuri** [comment]
![image](https://user-images.githubusercontent.com/40571891/79995692-7e0db100-84f2-11ea-9e3d-5216df742ff4.png)

**Comment by mikanmatsuri** [comment]
横めちゃ長、縦短い

**Comment by mikanmatsuri** [comment]
別イシューで対応済
