### ISSUE TITLE
レスポンシブデザインCSSでアスペクト比をどのように使用したいのか考えて整理する

### ISSUE THREAD

**Issue by mikanmatsuri** [mikanmatsuri/portfolio#27]

**Comment by mikanmatsuri** [comment]
・スマホサイズ　16：9
アスペクト比をどのように使用したいか分からないから、photoshopで新しくスマホ用のデザインを作成する
※本来、スマホ用、タブレット用のデザインをphotoshopで作成するのが普通なため。作成しない場合、PCだけの対応に変更してレスポンシブは考えないこととする

・タブレットサイズ　16:10
アスペクト比をどのように使用したいか分からないから、photoshopで新しくタブレット用のデザインを作成する
※本来、スマホ用、タブレット用のデザインをphotoshopで作成するのが普通なため。作成しない場合、PCだけの対応に変更してレスポンシブは考えないこととする

・PCサイズ　16：9
photoshopのデザインと違う部分だけを確認し直す

今後の対応
・レスポンシブに出来ないため、vhとvwの使用を辞めて、％でサイズ指定変更する
・文字だけcalcを使って、px指定する
・

**Comment by AlexanderKupriyanov** [comment]
タイトルが5w1h形式になってない、直して

**Comment by mikanmatsuri** [comment]
別イシューで対応済
