### ISSUE TITLE
Photoshopで自己紹介のデザインを作る

### ISSUE THREAD

**Issue by mikanmatsuri** [mikanmatsuri/portfolio#54]
・名前
・簡単な経歴
・趣味
・好きなもの
・今、勉強していること
を記載する予定

**Comment by AlexanderKupriyanov** [comment]
年齢(20代とかでいい)、住所(東京世田谷区でいい)
短期的な目標と長期的な目標、5年先自分どうなっているか
あとは面接でよくある質問ぐぐって

**Comment by AlexanderKupriyanov** [comment]
写真

**Comment by mikanmatsuri** [comment]
①上記の情報を踏まえ、スマホたてとよこ、PCワイヤーフレームを作成する
②デザインを練る
③完成したデザインを基にコーディング

**Comment by AlexanderKupriyanov** [comment]
ワイヤをノートでペンで1時間以内5パターンくらい作って
人のブログとかを参考にして
乗せる情報は上記の通り

**Comment by mikanmatsuri** [comment]
![about-1](https://user-images.githubusercontent.com/40571891/84458812-cea6bc80-aca0-11ea-98e6-d4eb305fe0d6.png)
![about-2](https://user-images.githubusercontent.com/40571891/84458811-ce0e2600-aca0-11ea-9d03-1736b271a73c.png)
![about-3](https://user-images.githubusercontent.com/40571891/84458807-ccdcf900-aca0-11ea-919a-5c1934940426.png)

**Comment by mikanmatsuri** [comment]
現在使用していない為、クローズ
